apiVersion: v1
kind: Service
metadata:
  name: chromosoft-service
  namespace: chromosoft-ns
spec:
  type: NodePort
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
